### ISSUE TITLE
Debian packaging of version 1.3.0

### ISSUE THREAD

**Issue by imincik** [linz/linz-bde-schema#117]
Debian packaging of version 1.3.0

**Comment by strk** [comment]
Ready for packaging: https://github.com/linz/linz-bde-schema/releases/tag/1.3.0

**Comment by strk** [comment]
Please also approve the two pending requests about targetting 1.3.1 and 1.4.0

**Comment by imincik** [comment]
Packaged and uploaded to 'test' branch.
