### ISSUE TITLE
Use "CREATE INDEX IF NOT EXIST" to detect if index exist

### ISSUE THREAD

**Issue by imincik** [linz/linz-bde-schema#125]
Use "CREATE INDEX IF NOT EXIST" to detect if index exist in schema creation scripts instead of

queries like this
```
IF NOT EXISTS (SELECT relname FROM tmp_bde_index WHERE relname='fk_app_par') THEN
    RAISE NOTICE 'Building fk_app_par';
    CREATE INDEX fk_app_par ON bde.crs_appellation USING btree (par_id);
END IF;
```

**Comment by strk** [comment]
`CREATE INDEX IF NOT EXISTS` was added in PostgreSQL 9.5 -- using that would mean dropping support for 9.3

**Comment by strk** [comment]
Reference:
- https://www.postgresql.org/docs/9.4/sql-createindex.html
- https://www.postgresql.org/docs/9.5/sql-createindex.html

**Comment by imincik** [comment]
No, we need to maintain 9.3 support.

**Comment by strk** [comment]
Then I'll close this, it isn't worth switching code based on version, right ?

**Comment by imincik** [comment]
> Then I'll close this, it isn't worth switching code based on version, right ?
yes
