### ISSUE TITLE
Upgrades from 1.1.2: Table bde.crs_work doesn't loose the "annotations" column

### ISSUE THREAD

**Issue by strk** [linz/linz-bde-schema#128]
As found via work in #127 upgrading from schema 1.1.2 to current master fails at dropping the "annotations" column from the `bde.crs_work` for some reason to be researched.

I guess the bug also exists in 1.2 and 1.3 branch, but didn't try that.

**Comment by strk** [comment]
Figured: the `BDE - 1.0.2: Remove annotations column from bde.crs_work` already existed in version 1.1.2, but it was bogus, in that it only removed the column IFF the table was versioned.

The patch was later fixed, but it won't be applied again because it results as being already applied.

**Comment by strk** [comment]
Moreover, the fixed version of the patch will never enter the database, because the `apply_patch` call will NOT install the new version of the patch, finding the old version already installed.

One fix to this problem could be to provide another patch ensuring it would work both when the column was removed and not removed. What do you think @palmerj  ?

**Comment by palmerj** [comment]
HI @strk has the column actually been dropped from all production databases? e.g prd1, prd2 and linzldsbde2 (which you now have a dump for)

**Comment by palmerj** [comment]
OK quick check is prd1 still has the column as no BDE patches have been applied in this database, but prd2 doesn't have the column (patch applied 2018-12-02). I don't have easy access to the linzldsbde2 dump or database

**Comment by palmerj** [comment]
So if linzldsbde2 doesn't have the column, then I think there is no problem to solve as the old patch wouldn't have been applied anywhere.

**Comment by strk** [comment]
The `bde.crs_work` table restored from `linzldsbde2` dump does NOT
have an `annotations` column.

So do we leave 1.1.2 upgrade untested ? In other words, will we document 1.1 as being an UNUPGRADEABLE version ?

**Comment by palmerj** [comment]
Sorry @strk. I don't  fully understand. Is 1.1.2 only dropping the annotations column? If so then yes it would worry about it and just document the issue.

**Comment by strk** [comment]
Releases 1.0 to 1.1 contain a broken patch to drop the annotations column (it only works IFF `table_version` is installed as an extension). The patch was fixed (using the same patch name) in the 1.2.x branch (not sure exactly which patch-level release).

So anyone who had installed up to version 1.1 in a database in which `table_version` was NOT installed as an extension, will still have the `annotations` column after upgrading to 1.2.x or later.

This will be confirmed by Travis (now testing upgrades) if we add the 1.1.2 version in the list of upgrade paths

So, if anyone started with version 1.1.2

**Comment by palmerj** [comment]
Thanks @strk. No LINZ systems have versions 1.0 to 1.1 installed with the patch applied. So I think this is not a problem.

**Comment by strk** [comment]
Ok then, I filed https://github.com/linz/linz-bde-schema/pull/129 to test upgrade from pre 1.0.2 version, so the patch did not exist. We can NOT test upgrades from versions from 1.0.3 to 1.1.2 because all of them have the broken patch and any proper install would apply all available patches, thus breaking upon upgrade. I'm ok with just documenting this by providing instructions about how to fix database when upgrading to 1.2.0 or later...

**Comment by imincik** [comment]
This task is still relevant.

**Comment by strk** [comment]
Still relevant, we want to document this I think.
