### ISSUE TITLE
Release version 1.4.0

### ISSUE THREAD

**Issue by strk** [linz/linz-bde-schema#131]
We need this to have a new debian package accepting tableversion and dbpatch for PostgreSQL versions 10 and 11

\cc @imincik

**Comment by imincik** [comment]
If no change is done outside of `debian` dir, we don't need to release new `linz-bde-schema` version.

**Comment by strk** [comment]
In that case I'll backport the debian/ changes in the release branch and assign packaging to you, ok ?

**Comment by strk** [comment]
wait, we already have those changes in linz-bde-schema 1.3 branch!

**Comment by imincik** [comment]
> In that case I'll backport the debian/ changes in the release branch and assign packaging to you, ok ?

yes

**Comment by strk** [comment]
> > In that case I'll backport the debian/ changes in the release branch and assign packaging to you, ok ?
> 
> yes

Done, I've also added support for PostgreSQL-12 in there, since I was
at it...

**Comment by strk** [comment]
Reopening, as we want to really release 1.4.0 now for the `stdout` support...

**Comment by strk** [comment]
Release ready: https://github.com/linz/linz-bde-schema/releases/tag/1.4.0
To be packaged: https://github.com/linz/linz-bde-schema/issues/137
