### ISSUE TITLE
Publish new Debian packages for 1.3, with updated Recommended PostgreSQL versions

### ISSUE THREAD

**Issue by strk** [linz/linz-bde-schema#133]
See 67268ee2ed30f7d035dbc404b760aeb5d509501c

**Comment by strk** [comment]
The last package on packagecloud for linz-bde-schema is 1.3.0-1linz~trusty1 which has PostgreSQL in its "Depends" rather than "Recommends". That is wrong as we can install the bde-schema to a remote PostgreSQL so there's no dependency. We could actually even drop that mention all at once.

I see debian/control in 1.3 branch has those packages in Recommends so I'm not sure how the debian package on packagecloud ended up having them in "Depends". Ideas @imincik ?

**Comment by imincik** [comment]
@strk ,

this is  linz-bde-schema_1.3.0-1linz~trusty1_all.deb `control` file content downloaded from Packagecloud:

```
Package: linz-bde-schema
Version: 1.3.0-1linz~trusty1
Architecture: all
Maintainer: Jeremy Palmer (LINZ) <jpalmer@linz.govt.nz>
Installed-Size: 247
Recommends: postgresql-9.6-tableversion (>= 1.4.0) | postgresql-9.5-tableversion (>= 1.4.0) | postgresql-9.4-tableversi
on (>= 1.4.0) | postgresql-9.3-tableversion (>= 1.4.0), postgresql-9.6-dbpatch (>= 1.2.0) | postgresql-9.5-dbpatch (>=
1.2.0) | postgresql-9.4-dbpatch (>= 1.2.0) | postgresql-9.3-dbpatch (>= 1.2.0)
Section: database
Priority: extra
Homepage: http://www.linz.govt.nz
Description: Provides the core BDE schemas and functions that are used
 for storing and accessing raw BDE unloads from the Landonline database
 system.
```

There are no packages in `Depends`

**Comment by strk** [comment]
Sorry, I was evidently wrong. it could be some package is not skipping recommends then. Can you upload anyway an updated one which includes postgresql-10 and -11 (and maybe -12) among the set of possibly recommended ?

**Comment by imincik** [comment]
I am now packaging

**Comment by imincik** [comment]
Package pushed in to `test` branch.

**Comment by strk** [comment]
Thanks, can you do https://github.com/linz/linz-lds-bde-schema/issues/143 next ?
