### ISSUE TITLE
Add reference to "raw BDE exports" format

### ISSUE THREAD

**Issue by strk** [linz/linz-bde-schema#14]
This code serves the purpose of storing and accessing `raw BDE exports`, so it would make sense to include (in the README.md file) a reference to a specification document describing that format.

**Comment by strk** [comment]
It looks like some format documentation is in the Perl library to read it:
https://github.com/linz/linz_bde_perl/blob/master/README.md
So maybe this repository could just contain a reference to the library (as it is using the library) and the formal specification will be linked from there (https://github.com/linz/linz_bde_perl/issues/1)

But still it would be important to document which version of the `raw BDE exports` format the current database schema is able to store/access.

**Comment by palmerj** [comment]
What do you mean by specification format? do you mean the BDE CRS format like this one on page 23 (4. DATA SUPPLY FORMATS) from this old document:

http://www.linz.govt.nz/system/files_force/media/file-attachments/landonline-bde-overview.pdf?download=1

If so then yes this information should be transferred into documentation in either linz_bde_copy or linz_bde_perl as this PDF document will disappear from the internet at some point, because the public LINZ "BDE" product is no longer available

**Comment by strk** [comment]
Yes, CRS format (in-file) and files organization
(level_0, level_5 etc.)

I've found a [tool](http://coolwanglu.github.io/pdf2htmlEX/)
to convert the PDF to HTML, which produces a
[nice output](http://strk.kbt.io/tmp/landonline-bde-overview.html),
even converting images to javascript code producing it !

It totals 2.6M (vs. ~800K of the PDF) but maybe it could be simplified
to only contain the information of interest and included in
linz-bde-perl.

```
-rw-r--r-- 1 strk src 2.6M May 25 09:36 landonline-bde-overview.html
-rw-r--r-- 1 strk src 795K May 25 09:30 landonline-bde-overview.pdf
```

**Comment by strk** [comment]
I see from [linz_bde_perl README](https://github.com/linz/linz_bde_perl/blob/master/README.md) that the `level_0` and `level_5` layout is called a `BDE repository`. So that's another thing to be documented.

For the purpose of this repository I'll just push a commit mentioning `linz_bde_perl` as the source of file format specification.

**Comment by strk** [comment]
Please review the text in https://github.com/linz/linz_bde_perl/pull/3, so that #18 will get the user to useful information there...
