### ISSUE TITLE
Publish bionic packages

### ISSUE THREAD

**Issue by strk** [linz/linz-bde-schema#143]
Once tested (#142)

**Comment by imincik** [comment]
This task is still relevant.

**Comment by strk** [comment]
Pushing build-area/linz-bde-schema_1.6.0-1linz~bionic1_all.deb... success!

**Comment by strk** [comment]
Reopening until we promote to production

**Comment by strk** [comment]
For the record, [Release 1.8.0](https://github.com/linz/linz-bde-schema/releases/tag/1.8.0) is available, for a new package

**Comment by imincik** [comment]
@strk , we are promoting packages from `test` repo branch to `prod` after BDE Processor UAT is done (https://github.com/linz/bde-processor-deployment/wiki/Production-Deployment#production-deployment). I think we don't need this ticket. Will close it.
