### ISSUE TITLE
Add comments for bde tables

### ISSUE THREAD

**Issue by strk** [linz/linz-bde-schema#15]
As the schema created by this code serves as a central place for different subsystems it would be important to document the schema as much as possible.

It is my understanding that an attempt is made to have the table match as closely as possible the file based tables in the source `raw BDE exports` (see  #14) but it is likely that the database presents specificities that are worth documenting.

Using `COMMENT ON` constructs to at least map each table to the corresponding file would be a start.

**Comment by strk** [comment]
This may wait for an automated way to generate the comments. I'm working on one such way but it's requiring more manual intervention than hoped for. Obtaining access to mappings may help: #54

**Comment by strk** [comment]
For the record: after the automated generation of table comments from LDS Data Dictionary document a few tables remain undocumented, so we should still find the official source of documentation.

Example undocumented tables: bde.crs_adj_obs_change, bdecrs_geodetic_network, bde.crs_image, bde.crs_mesh_blk, ... (maybe they are deprecated tables now shown on LDS ?)

**Comment by palmerj** [comment]
> Example undocumented tables: bde.crs_adj_obs_change, bdecrs_geodetic_network, bde.crs_image, bde.crs_mesh_blk, ... (maybe they are deprecated tables now shown on LDS ?)

See #54 for reason why
