### ISSUE TITLE
Add table 'bde_control.upload' to 'all_bde' publication

### ISSUE THREAD

**Issue by imincik** [linz/linz-bde-schema#159]
This is useful for inspecting BDE data version on subscriber side.

**Comment by strk** [comment]
bde_control schema is created by [linz-bde-uploader](https://github.com/linz/linz-bde-uploader) so should probably be managed by a different publication (although there's a [debatable dependency](https://github.com/linz/linz-lds-bde-schema/issues/77) of this schema to that one...)

**Comment by imincik** [comment]
Issue moved to [linz/linz-bde-uploader #237](https://github.com/linz/linz-bde-uploader/issues/237) via [**ZenHub**](https://www.zenhub.com/)
