### ISSUE TITLE
Define a versioning policy

### ISSUE THREAD

**Issue by strk** [linz/linz-bde-schema#16]
It might be useful to define the semantic of bde schema version.
So far there's a `bde.bde_version()` function which returns the version of this package, but it is currently set to `dev` so doesn't make much sense.

Traces of versioning are in the [CHANGELOG.md](CHANGELOG.md) and other traces are in the [patches](https://github.com/linz/linz-bde-schema/blob/master/sql/99-patches.sql) file. From these traces I can see that a 3-numbers version is used (Major.Minor.Patch) but so far only the third number (Patch) was incremented. As some releases actually changed the schema (1.0.2 for example removed some columns) I'd consider using upper versions to encode the change.

A possible guide could be:
  - Increment Major (setting Minor and Patch to 0) when the change would make it impossible to restore a data-dump made from a previous version (drop a table, drop a column, change a column name, ...)
  - Increment Minor (setting Patch to 0) when adding a new database object (table, column, view, ...) in a way that clients may rely upon, making it easy for clients to require a version by only specifying Major.Minor.
  - Increment Patch when the change only affects performance or correctness and not client API

Once a policy is agreed upon, creating milestones in this github repository would be advisable to better organize changesets. For example the new view (#7) would need to go in a 1.1.0 milestone because it introduces a new object (and the QGIS Plugin will want to request 1.1+ version to work correctly)

\cc @imincik @palmerj  @SPlanzer

**Comment by palmerj** [comment]
Hi Sandro, yes fully agree with your comments. The 1.0.2 patch was a mistake and should have been 1.1.0. Actually we already have a policy for this, we just were not applying it! See

https://github.com/linz/data-services-upgrade/wiki/Software-Development-Guidelines

**Comment by strk** [comment]
Thanks for the pointer. May I suggest to qualify the `dev` version with the target release in each branch ?
That is, the branch targetting 1.2.4 would be versioned `1.2.4-dev`. That way you can tell which development version was installed (even better would be to include the commit hash, as in `1.2.4-dev-<hash>` but at least the target version would help)

**Comment by imincik** [comment]
@strk , it was my idea to always use `dev` as version in development branch (like master) to prevent people installing something from development branch as an released version.

Using `dev` as version name doesn't require to update version when we release new version, but it doesn't work for example in Perl packages (Perl is complaining). I am OK with using `VERSION-dev`, but it needs to be applied at least for all BDE Processor components

**Comment by strk** [comment]
I think https://github.com/linz/data-services-upgrade/wiki/Software-Development-Guidelines and #37 solved the problem for this repository
