### ISSUE TITLE
 Grant table_version sequence privileges to bde_dba

### ISSUE THREAD

**Issue by strk** [linz/linz-bde-schema#170]
Followup to #70 ... we granted privileges to tables but not to _sequences_.
Generally not needed, but it sounds weird that `bde_dba` cannot read `table_version.revision_id_seq` (while it can read `table_version.revision`).

So.. this ticket is to grant additional permissions to table_version, as we did in #70

(maybe all permissions on sequences and functions?)

\cc @palmerj

**Comment by palmerj** [comment]
I assume bde_dba has rights to read everything because it's the owner of the objects... but yes we should be consistent

**Comment by imincik** [comment]
I think it is good to do for consistency.

**Comment by strk** [comment]
#171 implements the grant (only SELECT, but for consistency we _might_ really want all privileges, comment there if you want it changed to include more perms)
