### ISSUE TITLE
Grant CREATE on database to bde_admin ?

### ISSUE THREAD

**Issue by strk** [linz/linz-bde-schema#173]
According to [current docs](https://github.com/linz/linz-bde-schema/blob/1.8.0/sql/01-bde_roles.sql#L41-L43) the `bde_admin` role is the one that has "the ability to edit data in the tables", but when using https://github.com/linz/linz-bde-uploader to do the editing (via BDE uploader) those permissions are not enough, because the uploader also creates "temporary" schema to upload the data to, see https://github.com/linz/linz-bde-uploader/blob/2.7.0/sql/02-bde_control_functions.sql.in#L290

Shall the `bde_admin` role also have `CREATE ON DATABASE` permission, to allow for that usage type ?

This lack of permission is preventing usage of `bde_admin` by linz-bde-uploader, see https://github.com/linz/linz-bde-uploader/pull/249#issuecomment-577136517

**Comment by strk** [comment]
A possible problem with this is that grants on database are NOT included in PostgreSQL dumps (from `pg_dump`). This means a schema-creation-time GRANT to database won't move around (and would need to be retargetted to new database anyway).

We might prefer having a run-time (rather than schema-creation time) grant for this.

**Comment by imincik** [comment]
> We might prefer having a run-time (rather than schema-creation time) grant for this.
I am ok with that.

**Comment by strk** [comment]
Ok then I'm closing this, runtime grant will be done by linz-bde-uploader, via https://github.com/linz/linz-bde-uploader/pull/251
