### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by imincik** [linz/linz-bde-schema#182]
### DEBIAN PACKAGE: linz-bde-schema

Last tag: debian/1.9.0-1linz_bionic1
commit e88505399a61d542205c652ca9d76936925adcdf
Author: Ivan Mincik <imincik@linz.govt.nz>
Date:   Tue Feb 11 14:43:11 2020 +0100

    [debian] Changelog update

New changes since last tag:
```
commit 078a547042d3cefb1cdaae3404ac4be40251d724
Author: Sandro Santilli <strk@kbt.io>
Date:   Wed Mar 4 14:41:04 2020 +0100

    Do not assume too much on tableversion/dbpatch loader errors
    
    They don't necessarely mean lack of stdout support, so check if
    that's the case
    
    Fixes #178

commit ad891466b017d27af8e4a4c24bb53e344d60c820
Author: Ivan Mincik <imincik@linz.govt.nz>
Date:   Tue Feb 11 14:43:11 2020 +0100

    [debian] Changelog update
```

**Comment by strk** [comment]
It's really very little things to justify a new release IMHO.
How about waiting for the change required to add LOL-3.21 field ? See #181 
It would be a release 1.10

**Comment by imincik** [comment]
I am afraid that it will be a problem to say what is really small change to release and what is not. And we might finish in situation that we left some small change unreleased for one year and once it was released with something worth to release it might break something and nobody will remember or we might not even work for LINZ at that time (in extreme case). That's why I want to release always everything to make sure we have it fresh in our brains.

**Comment by imincik** [comment]
Now we need to release because of #183

**Comment by imincik** [comment]
Due fact that we are very late with BDE Processor UAT I packaged 1.9.0 with dependencies fixed and pushed to test.
