### ISSUE TITLE
Add table columns documentation

### ISSUE THREAD

**Issue by strk** [linz/linz-bde-schema#200]
A lot of BDE table columns are foreign key to other table's columns, but such information is not encoded by proper referential integrity constraints. This ticket is to at least DOCUMENT such relations via comments on columns.

\cc @iharrison @billgeo @imincik

**Comment by strk** [comment]
The table documentation was added with commit 9f6cb5bfd7847f2e9aeec484980c11125d5c7a7c using an ad-hoc script stored in this repository: `tools/dict2comment.pl` - maybe the script could be amended to also include columns description, assuming such description is present in source document https://data.linz.govt.nz/documents/?q=full+dataset+description

References #15 and https://github.com/linz/linz-lds-bde-schema/issues/229

**Comment by strk** [comment]
I verified column documentation IS available in the PDF that can be downloaded from data.linz.govt.nz, but we also have an XML version that is only internal, according to https://github.com/linz/linz-bde-schema/issues/54#issuecomment-348141643

Would it be possible to sollecitate authors of thosoe XML to review the information in them and split private from public info and figure out a way to manage such info in git repositories ? @billgeo

**Comment by billgeo** [comment]
> Would it be possible to sollecitate authors of thosoe XML to review the information in them 

Not sure who authors it, but I can try and find out. @palmerj any thoughts on who should I talk to? Brian?

> and split private from public info

Not sure what you mean by that? You mean which columns are public (published on LDS)?

**Comment by palmerj** [comment]
internal ML version is managed by Datacom. @stuart-datacom will be able to tell you about it.

**Comment by billgeo** [comment]
> Would it be possible to sollecitate authors of thosoe XML to review the information in them and split private from public info 

Hi @stuart-datacom, are you able to assist with this?

**Comment by billgeo** [comment]
@strk , Brian Evans from property rights said this.

> If you are only looking at the Landonline Schema for the subset of the data that is exported to LDS that’s fine.  
> If however you want to consider the full schema then you should definitely exclude tables and columns that relate to security and DVO management. That may involve a bit of work to identify.
> To avoid any confusion around availability of data I strongly suggest that you also exclude Workspace and staging tables as the former is private and potentially commercially sensitive data  (ie not yet submitted to LINZ) and the latter is data that is in an interim state.  
> There will be some tables like workflow where the data should not be considered public information but you may still need the schema if processing data for internal reporting.

Are we able to ensure we only extract schema info for tables published on the LINZ Data Service? A filter of some kind? Or would there be a danger we could include dvo/dva, security or workflow related stuff?

**Comment by stuart-datacom** [comment]
Hmmm.. the “we” worries me. I will either supply the Powerdesigner model file or not. And that will include everything. If Brian wants you to filter (because most of the database schema is not involved in LDS) then that is something I will not be doing.

Landonline exports data via a series of view definitions. The views may be joining or filtering base tables, and selecting a subset of the columns. Many Landonline tables are not involved in the views, so are not involved in the data export.

The text data files created are then sent to different systems including the Management Reporting systems, CRM and LDS i.e. not all the exported data may be received from LDS as it is intended for different systems.

So although the LDS schema is based on the Landonline schema, there are a couple layers of indirection in there.

The Powerdesigner model file only has the table metadata.

You would need to look at the text export definitions to see what is exported. Then if it is a view, look at the view source to determine what tables and columns are involved, then look at the downstream processing to which ones are supplied to LDS. Then process the Powerdesigner model file to extract the meta-data for the source tables and columns that you have identified.

Like .. that sounds like a substantial investment in time.

**Comment by palmerj** [comment]
What's been done in the past (since Brian/Noel first managed the Public BDE Data dictionary PDF doc) is a manual copy/change process from the powerdesigner XML to the data dictionary metadata that is maintained for LDS. I don't think it's practical to automatically take the definitions from the powerdesign XML to the LDS metadata. As pointed out by @stuart-datacom and Brian there are many table, columns and even column descriptions that need to change for the public LDS table views. But the powerdesigner XML should still be provided to give a starting point for any new tables or columns that are required on LDS

**Comment by billgeo** [comment]
Hi @strk do you still want the XML for this? I have a copy of the LOL 3.22 version.

**Comment by strk** [comment]
yes, thanks

**Comment by strk** [comment]
I've run the dict2comments.sh script again against an updated LDS data dictionary (2.6 from November 2019).
The diff shows that table identifiers changed since the last run, like:
```
diff --git a/sql/06-schema_comments.sql b/sql/06-schema_comments.sql
index 01bb2f5..a5c4ab9 100644
--- a/sql/06-schema_comments.sql
+++ b/sql/06-schema_comments.sql
@@ -1,14 +1,11 @@
--- Generated by tools/dict2comment.pl on Mon Nov 27 17:01:06 CET 2017
--- From input:
--- LDS Data Dictionary and Data Models - October - 2016 Version 2.3
-
+-- Generated by ../../linz-bde-schema/tools/dict2comment.pl on Tue Sep  1 18:57:40 CEST 2020
 
 COMMENT ON TABLE bde.crs_action IS $DESC$
 Instruments can be made up of one or more actions.
 
 Actions are used to perform the actual operations of titles transactions.
 
-https://data.linz.govt.nz/table/1702
+https://data.linz.govt.nz/table/51702
 $DESC$;
 
 COMMENT ON TABLE bde.crs_action_type IS $DESC$
@@ -16,33 +13,33 @@ Instruments can be made up of one or more actions.
 
 Actions are used to perform the actual operations of titles transactions. This table contains all the valid action types.
 
-https://data.linz.govt.nz/table/1728
+https://data.linz.govt.nz/table/51728
 $DESC$;
 
 COMMENT ON TABLE bde.crs_adjust_coef IS $DESC$
 Adjustment Coefficient is a set of control parameters used by an Adjustment Method in the Generate Coordinate/Adjustment process.
 
-https://data.linz.govt.nz/table/1704
+https://data.linz.govt.nz/table/51704
 $DESC$;
 
 COMMENT ON TABLE bde.crs_adjust_method IS $DESC$
```

Is it normal that table identifiers change between LDS versions ?

**Comment by iharrison** [comment]
The change looks like the difference between the LDS ids before and after it was migrated off Datacom infrastructure to the Kx platform.

**Comment by strk** [comment]
@iharrison are you able to provide the XML sources for that documentation, so that I can upgrade all tables at once ?

**Comment by strk** [comment]
The other difference with older document is that some deprecated tables, previously included in documentation (like crs_bde_elect_place) are not completely absent from the doc. Should we drop the comment on the table, in this case ? I'd rather not...

**Comment by billgeo** [comment]
Hi @strk Here's one for LOL3.22 (published in March I believe). Is this what you are after?

I've put it here, you should be able to access with your LINZ credentials. 

https://linzsrm-my.sharepoint.com/:u:/g/personal/bmnelson_linz_govt_nz/ESdo-j0TVAdLvWKiAunFjOMB7eOq26Hc_l5KeCTV3m8pSw?e=OkxuOr

**Comment by strk** [comment]
That link downloads a .pdm file
It's NOT what I was after. What I got, in the past, from @palmerj, was
a .zip file with .xml files in it, the .xml files contained
_documentation_ for each table and table column.

**Comment by billgeo** [comment]
Ah okay. Do you have an example of those files that I can send to the Landonline person? It might help get the right thing.

**Comment by strk** [comment]
I can't find the file but I see it referenced in tickets as having name like `DataDictionary-3.17.xml`

**Comment by stuart-datacom** [comment]
OK. I know what you are after. 
We generate a new version at deployment of each major release ( 3.17, 3,18, 3,19, ,,,, 3.21, 3.22). 3.22 is the current Landonline prod version (and 3.23 is being prepared).
As an added complication we installed 3.22.11 but then patched to 3.22.14 - the difference being some 3.23 changes that LINZ required to be deployed "early". There were schema changes in that patch - the table CRS_TTL_INST_PROTECT (which I  think is what you are after).
I can provide the 3.22 version - which will not have CRS_TTL_INST_PROTECT .
I can generate an interim 3.23 version. This is not necessarily the final version as 3.23 is still being developed. It will also have unrelated 3.23 changes that are not yet in production.

**Comment by billgeo** [comment]
Hi Stuart. Any chance you could provide 3.22 and 3.23-dev? It would be quite useful to get these whenever they are developed/published as well. Would there be someway to be notifed of a new version?

**Comment by strk** [comment]
I can extract just the crs_ttl_inst_protect table documentation from
the interim (3.23-dev) XML, no problem about the extra tables.

**Comment by strk** [comment]
Next step here: fetch documentation from the markdown in linz-lds-bde-schema repository and use those to extract table comments (up to columns)

**Comment by strk** [comment]
I just realized that the linz-lds-bde-schema package already installs comments for columns of all bde tables, so this issue can be closed as unneeded. Just load linz-lds-bde-schema to get all comments
