### ISSUE TITLE
Production Ubuntu package reports 'dev' version

### ISSUE THREAD

**Issue by imincik** [linz/linz-bde-schema#203]
Production Ubuntu package reports 'dev' version

`BDE_SCHEMA="1.12.0dev"`

**Comment by strk** [comment]
1.12.0 was NOT released yet so no such package should be in production. But I see a https://packagecloud.io/linz/prod/packages/ubuntu/bionic/linz-bde-schema_1.12-start-linz~bionic_all.deb package so now ... how did that package ever get to production ? It must have been a manual promotion! If this ever got to actual production we'll need to release a 1.12.0 with no change for the sole purpose of getting out of this mess

**Comment by strk** [comment]
I've now release 1.12.0 so when it is promoted to production we should have this issue fixed
