### ISSUE TITLE
Release 1.12.1

### ISSUE THREAD

**Issue by SPlanzer** [linz/linz-bde-schema#207]
To address [linz-bde-uploader/issues/279](https://github.com/linz/linz-bde-uploader/issues/279) a release must be made. 

Looking at the [tags](https://github.com/linz/linz-bde-schema/tags) the last release was 1.12.0. - This release will be 1.12.1

Steps to release 1.12.1:
- [x] Review PR #212
- [x] Update version in Makefile
- [x] Tag release branch `release-1.12` with `1.12.1`
  * This will trigger packaging 

\* Note, steps are as per: https://github.com/linz/bde-processor-deployment/wiki/Release-and-Packaging

**Comment by strk** [comment]
All done.
Release: https://github.com/linz/linz-bde-schema/releases/tag/1.12.1
Package: https://packagecloud.io/linz/test/packages/ubuntu/bionic/linz-bde-schema_1.12.1-linz~bionic_all.deb
