### ISSUE TITLE
Perform UAT for release 1.12.1

### ISSUE THREAD

**Issue by SPlanzer** [linz/linz-bde-schema#208]
Note this is dependent on the completion of #207 

UAT for release 1.12.1 must be conducted following https://github.com/linz/bde-processor-deployment/wiki/BDE-Processor-UAT

**Comment by billgeo** [comment]
@imincik has suggested we don't need to do this for such a simple bug fix if we are confident the code is low risk.
To deploy he said,

> Just add patch to extend this field and then build bde-schema package in test repo and then promote it in to prod repo and manually lauch BDE Processor and it will pick it up automatically and migrate schema

**Comment by palmerj** [comment]
I'm ok with this.
