### ISSUE TITLE
Remove updates for Statist Areas from the BDE

### ISSUE THREAD

**Issue by palmerj** [linz/linz-bde-schema#23]
Statist Areas are now all but deprecated and LOL is not the official source for this information.
- [ ] check who is using this and move to alternative source
- [ ] remove from updates for BDE processor (should leave the table there for historic purposes)

**Comment by palmerj** [comment]
Moved from https://github.com/linz/linz_bde_uploader/issues/39

**Comment by strk** [comment]
- [ ] document tables as being deprecated (see also #15)

**Comment by strk** [comment]
We're talking about crs_statist_area here, right ? @billgeo since which LoL version was that table deprecated ?

**Comment by strk** [comment]
The `Statist Area` table is mentioned/documented in  `Landonline Bulk Data Extract - Overview v28.0 – June 2014`

**Comment by billgeo** [comment]
As discussed. It looks like this table is being updated every few months with 68 new records, so technically not deprecated. 

Ben Jones said the authoritative source for this data was moved to Statistics NZ in early 2016. So we probably should have deprecated it around then. And people (internal and external) should go to the authoritative source if they want this data. 

If we get a list of all LOL releases with relevant changes from LOL team then we should see this change.

**Comment by strk** [comment]
So the only thing to do here is really only within https://github.com/linz/linz_bde_uploader to remove  the table from the default configuration of which tables get to be updated ?

**Comment by strk** [comment]
This repository only contains the schema, what is updated and what not is determined by the uploader configuration so I think https://github.com/linz/linz_bde_uploader/issues/39 makes sense to exist (in case there's a default configuration there)

**Comment by strk** [comment]
I'm closing this as non actable. Updates removal is discussed in https://github.com/linz/linz_bde_uploader/issues/39 and there's nothing to do here in linz-bde-schema as we don't have clear information about deprecation and versions. Feel free to reopen or maybe better file another ticket when ideas are clearer about what needs to be done.
