### ISSUE TITLE
Review VOLATILE state of functions (some may be STABLE instead)

### ISSUE THREAD

**Issue by strk** [linz/linz-bde-schema#27]
As `bde.bde_get_combined_appellation` and `bde.bde_get_par_stat_act` have been found called once for every record of big tables and accounting for a big slice of time it takes to run simplified layers maintainance functions (by `linz-lds-bde-schema` functions) it should help to set these functions as `STABLE` instead of `VOLATILE` so that the planner might call them just once for a given set of parameters.

Or, more generally, it makes sense to be correct about the function internals, and `VOLATILE` should only be for functions that can *change* the database, or those you want to allow changing return within the same statement.

See https://www.postgresql.org/docs/9.3/static/xfunc-volatility.html

\cc @palmerj

**Comment by strk** [comment]
PR #28 marked as STABLE the `bde.bde_get_combined_appellation` and `bde_get_app_specific` functions. Still left:

- bde_get_desccode
- bde_write_appellation
- bde_get_charcode
- bde_get_par_stat_act
- bde_get_dataset

**Comment by imincik** [comment]
Good job, thanks @strk . I hope it will make a difference.
