### ISSUE TITLE
Refactor schema creation/update SQL to allow overrides ?

### ISSUE THREAD

**Issue by strk** [linz/linz-bde-schema#53]
Current schema creation script (`02-bde_schema.sql`) skips doing anything if an `bde` schema exists in the database. This means any change in schema must be done either outside of that file or as a dbpatch based patch. As time passes it may become hard to maintain those schemas as the code for them would be spread across multiple files (`02-bde_schema.sql` for the oldest version and `99-patches.sql` for any subsequent change). Is it intended to be like that, to have an history of changes or not ?

If history of changes is what we want, should table comments (#15, #52) be all put in patches too ?

**Comment by palmerj** [comment]
I would suggest this:

* Add changes to main schema file to make it reflect current state
* Craft patches to be idempotence so if the schema doesn't need the change it doesn't run. e.g if column exists; datatype change or constraint has change already. Functions or comment are safe to run in all cases I think.

The only issue I see with this approach is if we need to deal with drop columns. IMHO we shouldn't drop columns or tables at any point.

**Comment by strk** [comment]
Another issue I see with this approach is that we'd always have a duplication (comment would be in main file *and* in patches). For comments we don't really need patches because setting a comment is always idempotent. The only reason to use patches would be to document how things changed across versions, but would mean continuously appending patches and having new installs always having to go through all steps in history. I don't really like that :)

**Comment by palmerj** [comment]
I'm happy with whatever solution you choose. If you want a complete schema current state schema script and upgrades on that schema I can't see another option using just SQL script. - but I haven't thought too long about it.  

The other option is to move to a higher level database change management deployment option e.g  http://sqitch.org/. If the whole perl applications was re-written in python then you could do the database change management with something like Django models and south migrations.

**Comment by strk** [comment]
Closing for now as for comments I found a different solution (put in separate file, would always override existing comments)
