### ISSUE TITLE
Provide mapping between pgsql table names and Data Dictionary names

### ISSUE THREAD

**Issue by strk** [linz/linz-bde-schema#54]
The table names found in the Data Dictionary document: https://data.linz.govt.nz/document/11095-lds-full-landonline-data-dictionary-and-models/ do not map cleanly to PostgreSQL table names. This ticket is to make available a mapping between the two.

**Comment by strk** [comment]
On further thoughts, I realize that the "lds-full-landonline" dataset is a *superset* of the BDE schema, so it is probably not the best source of information about BDE tables. The official information, I guess, should come from LandOnLine, which is where BDE files come from.

In an ideal world if LDS (data.linz.govt.nz) uses this schema in its backend, it could extract the description from the PostgreSQL Table description (and bde_ext and lds table descriptions from their own PostgreSQL table descriptions).

**Comment by strk** [comment]
The current mapping I've embedded in https://github.com/linz/linz-bde-schema/blob/master/tools/dict2comment.pl (see __END__ section) - finding the correct source of information about BDE tables is still an open task.

**Comment by palmerj** [comment]
This is a spreadsheet we used when setting up the project to release the data back in 2014: https://docs.google.com/spreadsheets/d/1E1vPG3REqxkjkdS6sfRXwukJmOH1g5mZbdlcbWRnRNo/edit?usp=sharing

You should be able to find the mappings there. The URLs are old before the migration to the cloud, but should still redirect the new ones. e.g https://data.linz.govt.nz/layer/2070 -> https://data.linz.govt.nz/layer/52070

**Comment by palmerj** [comment]
> On further thoughts, I realize that the "lds-full-landonline" dataset is a superset of the BDE schema, so it is probably not the best source of information about BDE tables. The official information, I guess, should come from LandOnLine, which is where BDE files come from.

Yes the LDS full landonline data dictionary only contains half of the bde.* tables and all bde_ext.* tables. The original source for the  (e.g 2001) the LDS full landonline data dictionary is the public BDE data dictionary (which I have provide you already as a zip), which was generated from "Landonline internal" data dictionary. Unfortunately the BDE and LDS data dictionaries had many changes that were not pushed back to the "Landonline internal" data dictionary, and in some cases it wouldn't make sense as we filter rows for the public LDS tables/layer versions. What I suggest is for the half of the bde.* tables that are internal to LINZ only that we get a latest copy of the Landonline data dictionary and then use that to get the comments. 

Also note that all of lds.* tables are defined in this data dictionary:  https://data.linz.govt.nz/document/11012-property-and-ownership-simplified-tables-data-dictionary/

**Comment by palmerj** [comment]
I have requested a copy of the internal Landonline data dictionary. I think it might be in a structured format, so I have asked for that

**Comment by strk** [comment]
Thanks, looking forward to it. It may make sense to document all tables from there rather than from the LDS document .

**Comment by palmerj** [comment]
> rather than from the LDS document
I don't think so as we improved the wording and descriptions a lot from the Landonline internal dictionary. But for the bde.* internal tables it will be the only source of information

**Comment by palmerj** [comment]
Here's the Landonline data dictionary for version 3.17. Not the XML is version 3.17, but the word document is 3.16 as it hasn't been generated yet (And I don't know how). So please work from the XML doc

[DataDictionary-3.17.zip](https://github.com/linz/linz-bde-schema/files/1511786/DataDictionary-3.17.zip)

**Comment by strk** [comment]
There seem to be still a need for mapping between table names and XML entity codes,
see d442e4c

**Comment by strk** [comment]
Actually there are 95 matches and 433 mismatches.
After applying those 95 comments there are still 10 tables in the `bde` schema which are not commented:
```
 crs_elect_place
 crs_mesh_blk
 crs_mesh_blk_area
 crs_mesh_blk_bdry
 crs_mesh_blk_line
 crs_mesh_blk_place
 crs_road_ctr_line
 crs_road_name
 crs_road_name_asc
 crs_street_address
```

**Comment by palmerj** [comment]
Should be possible via the code XML tag to get the table name e.g

<code>CRS_ADJ_OBS_CHANGE</code>, then no mapping is needed

**Comment by palmerj** [comment]
```
 crs_elect_place
 crs_mesh_blk
 crs_mesh_blk_area
 crs_mesh_blk_bdry
 crs_mesh_blk_line
 crs_mesh_blk_place
 crs_road_ctr_line
 crs_road_name
 crs_road_name_asc
 crs_street_address
```

Ah yes, that because they have been removed from the current production database, and hence the documentation. You need to go back to an older version of the schema. Our objective system is down for it's nightly backup, back I will try to find an older version for you tomorrow and post it here

I believe they have also been removed from the LDS full landonline data dictionary as of October 2016. @vlindsay should however be able to give you access to the older documentation.

**Comment by strk** [comment]
And what about the 433 tables missing from linz-bde-schema ?
How was it choosen which BDE files to include and which one not to include in this BDE schema ?
For example I see many tables starting with "crs_" which are not in the bde-schema, like:
```
ERROR:  relation "bde.crs_wrk_check_list" does not exist
ERROR:  relation "bde.crs_work_doc" does not exist
ERROR:  relation "bde.crs_work_notice" does not exist
ERROR:  relation "bde.crs_work_chk" does not exist
```

**Comment by palmerj** [comment]
It was decided not to make this information public, due to low value, or private information. Those table you like above as for internal QC workflow processes

**Comment by strk** [comment]
Ok then please see #57, I manually copied to the 06-schema_comment.sql file the generated comments for the tables which were not documented by parsing previous (LDS) document.

So this is still a manual process and we're still missing documentation for some of the tables. We could improve this in the future but for now I think it's enough to finalize a 1.1.0 release of this package (needed to unblock further development on BDE processor deployment)

**Comment by palmerj** [comment]
> Ok then please see #57, I manually copied to the 06-schema_comment.sql file the generated comments for the tables which were not documented by parsing previous (LDS) document.

Great thank you

> So this is still a manual process and we're still missing documentation for some of the tables

Is it just the ten tables you listed above? You will be able to find descriptions of those tables in historic "BDE" data dictionaries that I have given you in the past. If you can wait until the morning we can get you the pre October 2016 documentation as mentioned above

**Comment by strk** [comment]
I can wait for more XML files to come, no problem.
The added comments are just the ones for the 12 tables not documented in the LDS Data Dictionary from October 2016 (Version 2.3). I dunno at which date the BDE DataDictionary version 3.17 was released...

**Comment by strk** [comment]
I've updated the xmldict2comment.sh script to accept a filename containing the DDL to create the target schema, the script would then only output `COMMENT ON` lines for tables which are found to be created by the DDL statement in that file (`CREATE TABLE ...`). But it turns out some tables appear as being created by 02-bde_schema.sql only because CREATE TABLE statements for them are present although in C-style comments (`/* .. */`). These are the tables:
```
ERROR:  relation "bde.crs_audit_detail" does not exist
ERROR:  relation "bde.crs_dealing" does not exist
ERROR:  relation "bde.crs_dealing_survey" does not exist
ERROR:  relation "bde.crs_inst_role" does not exist
ERROR:  relation "bde.crs_job" does not exist
ERROR:  relation "bde.crs_job_task_list" does not exist
ERROR:  relation "bde.crs_process" does not exist
ERROR:  relation "bde.crs_req_det" does not exist
ERROR:  relation "bde.crs_req_hdr" does not exist
ERROR:  relation "bde.crs_req_item" does not exist
ERROR:  relation "bde.crs_task_list" does not exist
ERROR:  relation "bde.crs_task" does not exist
```

Ok to drop those commented-out snippets from repository ? Or is there any plan to get them back ?
Or I should make the script smarter to support C-style comments too..

**Comment by palmerj** [comment]
Document sent to allow you to get missing table

**Comment by palmerj** [comment]
> Ok to drop those commented-out snippets from repository ? Or is there any plan to get them back ?

Yes ok to drop

**Comment by strk** [comment]
Thanks, dropped with 171719dd5320432417a4566fcda8457b938dfead - the missing tables I've added by parsing DataDictionary-3.17.xml only ones missing comments now are mesh block tables, which I understand have been recently deprecated.

**Comment by strk** [comment]
I'm calling this done, for the moment it seems to be enough.

**Comment by imincik** [comment]
Thanks @str
