### ISSUE TITLE
[debian] drop package dependency on PostgreSQL/PostGIS/dbpatch

### ISSUE THREAD

**Issue by strk** [linz/linz-bde-schema#55]
The linz-bde-schema files are not strictly dependent on postgresql/postgis/dbpatch because all of them are only required to be on the *target* database system, not necessarely the same as the system from which linz-bde-schema is installed.

See also https://github.com/linz/linz_bde_uploader/issues/141

**Comment by imincik** [comment]
I agree. Thanks

**Comment by strk** [comment]
I guess this is worth doing before tagging 1.1.0 - last issue missing

**Comment by imincik** [comment]
Thanks @strk
