### ISSUE TITLE
E.g is separated by newline

### ISSUE THREAD

**Issue by palmerj** [linz/linz-bde-schema#58]
https://github.com/linz/linz-bde-schema/blob/d442e4c31eacdb8857988c9b2e608d1741c0d750/sql/06-schema_comments.sql#L459

**Comment by strk** [comment]
Eh, that's what you get from converting the PDF to an HTML and then HTML to text...
Should I re-generate that file fully from just the BDE XML and forget about the LDS document ?

**Comment by strk** [comment]
Ah now I remember it's actually the text-to-sql tool fault, it tries to be smart and leave an empty line after the first sentence, which is assumed ending on the first period, which is wrong in this case. I could try to make it smarter and recognize "e.g." ...

**Comment by strk** [comment]
But again: improving that script is only worth if we think we'll keep using LDS Data Model document to generate those comments

**Comment by strk** [comment]
This is the code snippet:
https://github.com/linz/linz-bde-schema/blob/1e435cbd4f2bd7f64047715af42adfa32a9ddda9/tools/dict2comment.pl#L71-L74

The snippet from the input is:
>    A Statistical Area Class, e.g. Territorial Authority, may have more than one version.

**Comment by strk** [comment]
well. fixed manually for now.

**Comment by palmerj** [comment]
> LDS Data Model document to generate those comments

I think we must as our datasets for LDS are different that the internal Landonline data tables. e.g filters on rows.

**Comment by palmerj** [comment]
> well. fixed manually for now.

Thanks!

**Comment by imincik** [comment]
Thanks
