### ISSUE TITLE
Publish 1.1.0 debian package

### ISSUE THREAD

**Issue by strk** [linz/linz-bde-schema#61]
Release is ready to be packaged:
https://github.com/linz/linz-bde-schema/releases/tag/1.1.0

**Comment by imincik** [comment]
Thanks @strk , I will do it ASAP.

**Comment by imincik** [comment]
Package uploaded in to Packagecloud `test` repository branch.

**Comment by imincik** [comment]
We are apparently missing some good way how to test packages after uploading to test.

**Comment by strk** [comment]
It looks like we're now having the test packages testing support, via `ANSIBLE_DEPLOYMENT_TEST_DEB_REPO=yes`, and this package have been tested enough to find a lack of support for the new appelation function from linz-bde-uploader (should be fixed in 2.4.0).

Also the testing allowed me to spot an unwanted runtime dependency of linz-bde-schema-load on `pg_config`, which seems to be only included in `libpq-dev` or `postgresql-server-xx-dev` packages, on debian (annoyingly). I've fixed the dependency in the release-1.1 branch, is it asking too much to release a 1.1.1 ?

**Comment by strk** [comment]
the (easier) alternative would be to install one of those two packages in the bde-processor machine, or a stub pg_config script...

**Comment by imincik** [comment]
> I've fixed the dependency in the release-1.1 branch, is it asking too much to release a 1.1.1 ?

No, I am OK with packaging a new version.

**Comment by strk** [comment]
I'm closing this issue as 1.1.0 debian package is published (although only in testing).
I would not even publish this to production, as we found it would break existing linz-bde-uploader installs anyway...
