### ISSUE TITLE
Grant table_version privileges to bde_dba

### ISSUE THREAD

**Issue by strk** [linz/linz-bde-schema#70]
The versioning script does not grant `bde_dba` sufficient privileges for usage (ie: no DELETE on `table_version.revisions`). This is needed for some operations. See #62

**Comment by strk** [comment]
The operation I found that privilege needed for was `bde_CompleteDatasetRevision` function in `linz-bde-uploader`: https://github.com/linz/linz_bde_uploader/blob/master/sql/02-bde_control_functions.sql.in#L2992 calling table_version.ver_delete_revision.

**Comment by strk** [comment]
While `table_version` itself does use `SECURITY DEFINER` in some functions, it does not set that flag for the `ver_delete_revision`. I'm not sure that function is intended to be part of the API or if it is good for linz-bde-uploader to use  it at all.

**Comment by palmerj** [comment]
From it is used to clean up hanging revision IDs thay are not used due to no data updates. But i do see it's undocumented

**Comment by strk** [comment]
and not set as security-definer (should it?) - should table_version expose a GC-like function in the API, so that unprivileged users can run it to cleanup unused revisions ?

**Comment by strk** [comment]
Real case scenario in which granting table_version privileges to bde_dba role is needed was found and is being handled in https://github.com/linz/linz-bde-schema/pull/91#issuecomment-376811603

**Comment by strk** [comment]
_changeset_revision also needs insert privileges

**Comment by strk** [comment]
inserts into `_changeset_revision` are done by the trigger function created upon enabling version on a table, that is: `table_version.SCHEMA_TABLE_revision()` function

**Comment by strk** [comment]
Ok the issue with `_changeset_revision` is that it is created by whoever owns the `ver_create_revision` function but the trigger placed on a table is owned by the owner of the table. The owner of the table does not have permissions to read the `_changeset_revision`. This seems to need be handled on the table_version side, see https://github.com/linz/postgresql-tableversion/issues/98
