### ISSUE TITLE
Changes to BDE schema for Landonline 3.17

### ISSUE THREAD

**Issue by billgeo** [linz/linz-bde-schema#80]
There are two schema changes for the BDE for Landlone 3.17 (currently due for release April 16th)

sap.crs.gz
2 new columns being added.
```
COLUMN   img_id                        integer NULL
COLUMN   description                   varchar NULL
```

xtrt.crs.gz
2 columns being removed.
```
COLUMN   tan_required                  char NULL
COLUMN   creates_tan                   char NULL
```

This change will also need to be made in the old BDE processor that the LDS is using.

**Comment by billgeo** [comment]
Hi @imincik, LOL 3.17 is scheduled for April 16/17. Can you please program this in with your team to work on soon? We will need changes to this repo and backport to https://github.com/linz/linz_bde_uploader_private. 

To improve on last time we should also test the schema changes in somehow. At least make sure there are no typos etc. Maybe @iharrison could assist with that?

**Comment by imincik** [comment]
Thanks @billgeo , I hope this one will be faster than previous one. Could be done next week (@strk )

**Comment by billgeo** [comment]
Just a reminder too that https://github.com/linz/linz-lds-bde-schema/issues/53 will also be released on April 16/17, so use that for patch management of this change. Although not sure if it would be worth backporting that too?

**Comment by strk** [comment]
According to `conf/table.conf` in `linz_bde_uploader` the `sap.crs.gz` input file gets uploaded to `crs_stat_act_parcl` table and the `xtrt.crs.gz` file to `crs_transact_type` table.

There are examples of dropping columns in `sql/99-patches.sql`, included dealing with `table_version`.

@billgeo I don't understand what you mean by using https://github.com/linz/linz-lds-bde-schema/issues/53 for patch management. Maybe just including LOL version in the patch name ?

**Comment by billgeo** [comment]
> I don't understand what you mean by using linz/linz-lds-bde-schema#53 for patch management.

@strk nevermind, I misunderstood what we were hoping to acheive with linz/linz-lds-bde-schema#53
