### ISSUE TITLE
Release version 1.2.1

### ISSUE THREAD

**Issue by strk** [linz/linz-bde-schema#97]
To include the fix for patches in extension-less table_version, see #96

**Comment by imincik** [comment]
@strk , are we able to release new version now ?

**Comment by strk** [comment]
Is #79 sorted out or do you think it needs action before shipping 1.2.1 ?

**Comment by imincik** [comment]
I don't now about anything blocking release

**Comment by imincik** [comment]
Sorry, we need to solve #79 or https://github.com/linz/bde-processor-deployment/issues/265 somehow

**Comment by strk** [comment]
1.2.1 is ready: https://github.com/linz/linz-bde-schema/releases/tag/1.2.1
