### ISSUE TITLE
Package 1.2.1

### ISSUE THREAD

**Issue by strk** [linz/linz-bde-schema#98]
When ready (see #97)

**Comment by strk** [comment]
Tag 1.2.1 is ready: https://github.com/linz/linz-bde-schema/releases/tag/1.2.1

**Comment by imincik** [comment]
Packages for Trusty and Xenial pushed to test branch on Packagecloud.

**Comment by strk** [comment]
Shall they be moved to production now?

**Comment by palmerj** [comment]
Yes please push to production if ready. I will re-open.

**Comment by strk** [comment]
Should be done :)
